# Generated by Django 4.2.13 on 2025-02-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_is_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
